WE-15260: adding globs to octostache-action
im-open/octostache-action pull request #4
Opened 2021-11-23 17:31 UTC by stevematney

2021-11-23 21:29 UTC, stevematney commented on README.md
> -| `output-files`             | false       | An optional comma separated list of files to output.<br/>If defined, the program assumes the index of the output file is the same as the index of the temp
It doesn't look like this `output-files` parameter was getting used at all.

2021-11-23 23:23 UTC, izep approved these changes, later dismissed

2021-11-23 23:25 UTC, danielle-casella-adams requested changes
The readme example will need it's version updated.

2021-11-23 23:36 UTC, stevematney commented
> The readme example will need its version updated.

I made it 2.1.0, and added `+semver:minor` to the commit, since this is a new feature.

2021-11-24 15:50 UTC, danielle-casella-adams approved these changes

2021-11-24 15:58 UTC, merged